//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyMed.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyMed.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bold16 {
            get {
                object obj = ResourceManager.GetObject("bold16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close32 {
            get {
                object obj = ResourceManager.GetObject("close32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ergebnisse werden ungenau. Gewicht ist keine gültige Zahl. ähnelt.
        /// </summary>
        internal static string HauptForm_BerechneBmi_Ergebnisse_werden_ungenau__Gewicht_ist_keine_gültige_Zahl_ {
            get {
                return ResourceManager.GetString("HauptForm_BerechneBmi_Ergebnisse_werden_ungenau__Gewicht_ist_keine_gültige_Zahl_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   ähnelt.
        /// </summary>
        internal static string HauptForm_DisplayRecordNumbers__ {
            get {
                return ResourceManager.GetString("HauptForm_DisplayRecordNumbers__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  von  ähnelt.
        /// </summary>
        internal static string HauptForm_DisplayRecordNumbers__von_ {
            get {
                return ResourceManager.GetString("HauptForm_DisplayRecordNumbers__von_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blutdruck: Datensatz:  ähnelt.
        /// </summary>
        internal static string HauptForm_DisplayRecordNumbers_Blutdruck__Datensatz__ {
            get {
                return ResourceManager.GetString("HauptForm_DisplayRecordNumbers_Blutdruck__Datensatz__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ernährung: Datensatz  ähnelt.
        /// </summary>
        internal static string HauptForm_DisplayRecordNumbers_Ernährung__Datensatz_ {
            get {
                return ResourceManager.GetString("HauptForm_DisplayRecordNumbers_Ernährung__Datensatz_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ernährung: Datensatz:  ähnelt.
        /// </summary>
        internal static string HauptForm_DisplayRecordNumbers_Ernährung__Datensatz__ {
            get {
                return ResourceManager.GetString("HauptForm_DisplayRecordNumbers_Ernährung__Datensatz__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Speichern der Daten ähnelt.
        /// </summary>
        internal static string HauptForm_ExecuteQuery_Fehler_beim_Speichern_der_Daten {
            get {
                return ResourceManager.GetString("HauptForm_ExecuteQuery_Fehler_beim_Speichern_der_Daten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler : ähnelt.
        /// </summary>
        internal static string HauptForm_GetDataConnection_Fehler__ {
            get {
                return ResourceManager.GetString("HauptForm_GetDataConnection_Fehler__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung zur Datenbankfehlgeschlagen ähnelt.
        /// </summary>
        internal static string HauptForm_GetDataConnection_Verbindung_zur_Datenbankfehlgeschlagen {
            get {
                return ResourceManager.GetString("HauptForm_GetDataConnection_Verbindung_zur_Datenbankfehlgeschlagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einfügefehler ähnelt.
        /// </summary>
        internal static string HauptForm_UltraGridAfterRowInsert_Einfügefehler {
            get {
                return ResourceManager.GetString("HauptForm_UltraGridAfterRowInsert_Einfügefehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Einfügen eines neuen Datensatzes in die Butdruck-Tabelle:  ähnelt.
        /// </summary>
        internal static string HauptForm_UltraGridAfterRowInsert_Fehler_beim_Einfügen_eines_neuen_Datensatzes_in_die_Butdruck_Tabelle__ {
            get {
                return ResourceManager.GetString("HauptForm_UltraGridAfterRowInsert_Fehler_beim_Einfügen_eines_neuen_Datensatzes_in" +
                        "_die_Butdruck_Tabelle__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Einfügen eines neuen Datensatzes in die Gewichtstabelle:  ähnelt.
        /// </summary>
        internal static string HauptForm_UltraGridAfterRowInsert_Fehler_beim_Einfügen_eines_neuen_Datensatzes_in_die_Gewichtstabelle__ {
            get {
                return ResourceManager.GetString("HauptForm_UltraGridAfterRowInsert_Fehler_beim_Einfügen_eines_neuen_Datensatzes_in" +
                        "_die_Gewichtstabelle__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newdocument32 {
            get {
                object obj = ResourceManager.GetObject("newdocument32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open16 {
            get {
                object obj = ResourceManager.GetObject("open16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste16 {
            get {
                object obj = ResourceManager.GetObject("paste16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste32 {
            get {
                object obj = ResourceManager.GetObject("paste32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pastespecial16 {
            get {
                object obj = ResourceManager.GetObject("pastespecial16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unorderedlist16 {
            get {
                object obj = ResourceManager.GetObject("unorderedlist16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
